[package]
name = "atomics"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic-wait = "1.1.0"


[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }

[[bench]]
name = "mutex_bench"

harness = false